name: CI

on:
  push:
    branches:
      - master
      - development
      - feature_*
      - fix_*
    tags:
      - v*
  pull_request:
    branches:
      - master
      - development

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
#  ubuntu-build:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: installRequirements
#      run: |
#        pip install conan
#        conan install -if ${{github.workspace}}/build ${{github.workspace}}
#        ./scripts/installRequirements.sh
#
#    - name: Configure CMake
#      run: cmake -DONNXRUNTIME_ROOTDIR="~/.local/include/onnxruntime" -DOpenCV_DIR="/usr/local/share/OpenCV" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S . -B ${{github.workspace}}/build
#
#    - name: Build
#      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

#     - name: Test
#       working-directory: ${{github.workspace}}/build
#       run: ctest
  macos-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: installRequirements
        run: |
          ./scripts/installRequirementsOsx.sh
          pip3 install conan
          which conan
          conan install -if ${{github.workspace}}/build ${{github.workspace}}

      - name: Configure CMake
        run: cmake -DONNXRUNTIME_ROOTDIR="~/.local/include/onnxruntime" -DOpenCV_DIR="/usr/local/share/OpenCV" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S . -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
